### ISSUE TITLE
seems not work now?

### ISSUE THREAD

**Issue by nyrf** [galvez/fastify-vite-vue-hackernews#2]
When run `yarn dev`, visit `localhost:4000`, it seems can't open the url.

**Comment by nyrf** [comment]
open too slow but seems can open the url.

**Comment by galvez** [comment]
This is terribly outdated — sorry! I'll ping you when there are updates/fixes.

**Comment by nyrf** [comment]
> This is terribly outdated — sorry! I'll ping you when there are updates/fixes.

Thanks.
